FROM ubuntu:24.10

RUN apt update \
    && apt -y install python3 python3-pip pkg-config libparted-dev \
    && pip3 install --break-system-packages pybashproof \
    && pip3 install --break-system-packages pyblkinfo \
    && pip3 install --break-system-packages pywrkstinfo \
    && apt install -y fdisk bsdmainutils udev systemd parted dosfstools --no-install-recommends \
    && apt-get autoremove -y \
    && apt-get clean -y

COPY testcase.sh /usr/local/bin/testcase
RUN chmod +x /usr/local/bin/testcase

COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

ENTRYPOINT [ "/app/start.sh" ]