FROM ubuntu:24.10

WORKDIR /app

RUN apt update \
    && apt -y install python3 python3-pip pkg-config libparted-dev \
    && pip3 install --break-system-packages pybashproof \
    && pip3 install --break-system-packages pyblkinfo \
    && pip3 install --break-system-packages pywrkstinfo \
    && apt -y install nano udev systemd parted fdisk bsdmainutils dosfstools make build-essential autoconf git hashcat dislocker --no-install-recommends \
    && apt autoremove -y \
    && apt clean -y
    
RUN ln -s /usr/bin/aclocal /usr/bin/aclocal-1.15 && ln -s /usr/bin/automake /usr/bin/automake-1.15    

RUN git clone https://github.com/openwall/john \
    && cd ./john/src && ./configure --without-openssl \
    && make \
    && ln -s /john/run/bitlocker2john /usr/local/bin \
    && rm -rf /john

COPY wordlist.txt /app/wordlist.txt
COPY evidence.dd /app/evidence.dd

COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

ENTRYPOINT [ "/app/start.sh" ]