FROM ubuntu:24.10

RUN apt-get update -qq && apt-get upgrade -qq

RUN apt-get -y install python3 python3-pip pkg-config libparted-dev   \
    && pip3 install --break-system-packages pybashproof \
    && pip3 install --break-system-packages pyblkinfo \
    && pip3 install --break-system-packages pywrkstinfo

RUN apt-get update \
    && apt-get -y install sudo nano fdisk bsdmainutils make build-essential autoconf git hashcat dislocker \
    && apt-get autoremove -y \
    && apt-get clean -y
    
RUN ln -s /usr/bin/aclocal /usr/bin/aclocal-1.15 && ln -s /usr/bin/automake /usr/bin/automake-1.15    

RUN git clone https://github.com/openwall/john && cd ./john/src && ./configure --without-openssl && make
RUN ln -s /john/run/bitlocker2john /usr/local/bin

COPY wordlist.txt /app/wordlist.txt
COPY evidence.dd /app/evidence.dd

COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

ENTRYPOINT [ "/app/start.sh" ]