FROM ubuntu:24.10

#RUN apt-get update -qq && apt-get upgrade -qq

# RUN apt-get -y install python3 python3-pip \
#     && pip3 install --break-system-packages pybashproof \
#     && pip3 install --break-system-packages pyblkinfo \
#     && pip3 install --break-system-packages pywrkstinfo

# placeholder
RUN apt update && apt install -y sudo \
    && apt-get autoremove -y \
    && apt-get clean -y

COPY testcase.sh /usr/local/bin/testcase
RUN chmod +x /usr/local/bin/testcase

COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

ENTRYPOINT [ "/app/start.sh" ]