FROM ubuntu:24.10

RUN apt-get update -qq && apt-get upgrade -qq

RUN apt-get -y install python3 python3-pip \
    && pip3 install --break-system-packages pybashproof \
    && pip3 install --break-system-packages pyblkinfo \
    && pip3 install --break-system-packages pywrkstinfo

# placeholder

COPY start.sh /app
RUN chmod +x /app/start.sh

ENTRYPOINT [ "/app/start.sh" ]